version: '3.8'

services:
  backend:
    build: .
    image: ${DOCKERHUB_USERNAME}/back-innovatech:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db-innovatech
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
    depends_on:
      - db-innovatech
    networks:
      - innovatech-net

  db-innovatech:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - innovatech-net

networks:
  innovatech-net:
    driver: bridge

volumes:
  db_data: