name: Deploy Backend & DB Stack

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy Backend Stack via Docker Compose
        run: |
          cd ~/innovatech-chile
          cp -r ${{ github.workspace }}/* .
          
          # Levanta el microservicio y su base de datos de apoyo de forma aislada
          docker compose up -d --build db-innovatech backend